[package]
name = "impl-stable-id-macro"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
const-fnv1a-hash = "1.1.0"
proc-macro2 = "1.0.76"
quote = "1.0.35"
syn = {version="2.0.48",features=["parsing"]}

[lib]
proc-macro = true
